# put here any directive needed only when deploying
# a special deploy_dir variable specifies the deployment location using rsync

baseurl: http://www.jesperkallgard.se
deploy_dir: jesperkallgard@gmail.com:/jesperkallgard.se/gh-pages
